### ISSUE TITLE
Support change in JIRA Comment WebHooks

### ISSUE THREAD

**Issue by Jeff-Lewis** [SymphonyOSF/App-Integrations-Jira#124]
It appears JIRA has [removed comments from their issue webhooks](https://ecosystem.atlassian.net/browse/ACJIRA-1225).  Comments are now only supplied in JIRA's [Comment Event webhooks](https://developer.atlassian.com/cloud/jira/platform/modules/webhook/).

Is there a plan to support JIRA's Comment Event Hooks? Currently, no comments in JIRA can be seen in Symphony using this integration.

Any info on the subject would be helpful. Thank you.

**Comment by luanapp** [comment]
Previously Jira was triggering two events when a comment was create/updated/deleted. We just watched one of them, because it had the issue info. Now they changed it to send only one event, which was the one we skipped.
There's a bug opened to solve this and soon it will be available

**Comment by Jeff-Lewis** [comment]
Hi @luanapp do you have a link to the opened bug for this issue?

**Comment by luanapp** [comment]
The bug link is a Symphony Internal one and I can't post it here. But the pull request #125 has the fix and you can check it
